name: Release
on:
  push:
    branches:
      - "main"
    paths:
      - 'package.json'
permissions:
  contents: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build

      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json  # Путь к package.json

      - name: Publish to npm (with provenance)
        if: steps.create_tag.outputs.successful == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - id: pack
        if: steps.create_tag.outputs.successful == 'true'
        run: echo "TGZ=$(npm pack --silent)" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        if: steps.create_tag.outputs.successful == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}  # Используем версию из созданного тега (например, v1.0.0)
          files: ${{ steps.pack.outputs.TGZ }}
          generate_release_notes: true
